### ISSUE TITLE
No command output 

### ISSUE THREAD

**Issue by n00bMk** [threatexpress/malleable-c2#5]
I am running the jquery-2.4.0.profile on my test lab. The stageless beacon reaches back to the team server. Unfortunately there is no  command output at all even with a sleep time set to 0.
Profiles from Raphael Mudge's  repo work fine.
Any  idea what is wrong here? 

Sample:
beacon> getuid
[*] Tasked beacon to get userid
[+] host called home, sent: 8 bytes
beacon> ps
[*] Tasked beacon to list processes
[+] host called home, sent: 12 bytes

**Comment by andrewchiles** [comment]
My first thought would be to check your teamserver console output for any C2 profile related errors to help narrow down the issue.
Are all comms occuring within a local lab environment or across the internet?

**Comment by n00bMk** [comment]
Thanks for your reply!
Got it sorted out thankns to a line in this [article](https://bluescreenofjeff.com/2018-04-12-https-payload-and-c2-redirectors/). 
"if your Cobalt Strike Malleable C2 profile contains an Accept-Encoding header for gzip, your Apache install may compress that traffic by default and cause your Beacon to be unresponsive or function incorrectly."

As my test lab had a redirector it made my beacon unresponsive to commands :)

Cheers!

**Comment by andrewchiles** [comment]
Yep gzip will mess you up. The safest option is to probably set `Accept-Encoding: identity` in your profile to prevent your Apache redirector (or anything between from compressing your traffic. You can disable that of course in your redirector, but I've seen egress network controls (probably BlueCoat proxy) break C2 comms due to encoding as well. Glad you got it worked out!
